
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import javax.swing.ImageIcon;// Necesario para 'new ImageIcon'
import java.awt.Image;        // Necesario para 'Image.SCALE_SMOOTH'
// Y la que te falta:
import javax.swing.Icon;      
/**
 *
 * @author USUARIO
 */
public class Heroes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Heroes.class.getName());

    /**
     * Creates new form Heroes
     */
    public Heroes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_image = new javax.swing.JLabel();
        btn_pepa = new javax.swing.JButton();
        btn_keroppi = new javax.swing.JButton();
        btn_cinammon = new javax.swing.JButton();
        btn_melody = new javax.swing.JButton();
        btn_badz1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_image.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_image.setText("jLabel1");
        txt_image.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_image, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 270, -1));

        btn_pepa.setBackground(new java.awt.Color(175, 190, 206));
        btn_pepa.setForeground(new java.awt.Color(0, 0, 0));
        btn_pepa.setText("pepa");
        btn_pepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pepaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 50));

        btn_keroppi.setBackground(new java.awt.Color(175, 190, 206));
        btn_keroppi.setForeground(new java.awt.Color(0, 0, 0));
        btn_keroppi.setText("keroppi");
        btn_keroppi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_keroppi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keroppiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_keroppi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, 50));

        btn_cinammon.setBackground(new java.awt.Color(175, 190, 206));
        btn_cinammon.setForeground(new java.awt.Color(0, 0, 0));
        btn_cinammon.setText("cinammon");
        btn_cinammon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_cinammon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cinammonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cinammon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 90, 50));

        btn_melody.setBackground(new java.awt.Color(175, 190, 206));
        btn_melody.setForeground(new java.awt.Color(0, 0, 0));
        btn_melody.setText("my Melody");
        btn_melody.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_melody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_melodyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_melody, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 50));

        btn_badz1.setBackground(new java.awt.Color(175, 190, 206));
        btn_badz1.setForeground(new java.awt.Color(0, 0, 0));
        btn_badz1.setText("badz");
        btn_badz1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_badz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_badz1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_badz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pepaActionPerformed
        // 1. Cargar el recurso de la imagen
    // Usamos 'pepaIcon' como un nombre de variable Java válido.
    ImageIcon pepaIcon = new ImageIcon(
        getClass().getResource("/Interfaz/pepa.jpg") // Usar la ruta absoluta para mayor robustez
    );

    // 2. Escalar la imagen al tamaño del JLabel (txt_image)
    Icon img_imagen = new ImageIcon(
        pepaIcon
            .getImage()
            .getScaledInstance(
                txt_image.getWidth(),  // Ancho del JLabel
                txt_image.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    txt_image.setIcon(img_imagen);
    }//GEN-LAST:event_btn_pepaActionPerformed

    private void btn_keroppiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keroppiActionPerformed

   ImageIcon keroppiIcon = new ImageIcon(
    getClass().getResource("keroppi.png")
);

    // 2. Escalar la imagen al tamaño del JLabel (txt_image)
    Icon img_imagen = new ImageIcon(
        keroppiIcon
            .getImage()
            .getScaledInstance(
                txt_image.getWidth(),  // Ancho del JLabel
                txt_image.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    txt_image.setIcon(img_imagen);
    }//GEN-LAST:event_btn_keroppiActionPerformed

    private void btn_cinammonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cinammonActionPerformed
        
   ImageIcon cinammonIcon = new ImageIcon(
    getClass().getResource("cinammon_roll.jpg")
);

    // 2. Escalar la imagen al tamaño del JLabel (txt_image)
    Icon img_imagen = new ImageIcon(
        cinammonIcon
            .getImage()
            .getScaledInstance(
                txt_image.getWidth(),  // Ancho del JLabel
                txt_image.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    txt_image.setIcon(img_imagen);
    }//GEN-LAST:event_btn_cinammonActionPerformed

    private void btn_melodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_melodyActionPerformed
        
   ImageIcon melodyIcon = new ImageIcon(
    getClass().getResource("my_melody.png")
);

    // 2. Escalar la imagen al tamaño del JLabel (txt_image)
    Icon img_imagen = new ImageIcon(
        melodyIcon
            .getImage()
            .getScaledInstance(
                txt_image.getWidth(),  // Ancho del JLabel
                txt_image.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    txt_image.setIcon(img_imagen);
    }//GEN-LAST:event_btn_melodyActionPerformed

    private void btn_badz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_badz1ActionPerformed
        ImageIcon badtzIcon = new ImageIcon(
    getClass().getResource("badtz.png")
);

    // 2. Escalar la imagen al tamaño del JLabel (txt_image)
    Icon img_imagen = new ImageIcon(
        badtzIcon
            .getImage()
            .getScaledInstance(
                txt_image.getWidth(),  // Ancho del JLabel
                txt_image.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    txt_image.setIcon(img_imagen);
    }//GEN-LAST:event_btn_badz1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Heroes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_badz1;
    private javax.swing.JButton btn_cinammon;
    private javax.swing.JButton btn_keroppi;
    private javax.swing.JButton btn_melody;
    private javax.swing.JButton btn_pepa;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_image;
    // End of variables declaration//GEN-END:variables
}
