/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial;
import javax.swing.ImageIcon;
import java.awt.Image;  
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class App extends javax.swing.JFrame {
    int numeroVidas = 5;
    int resCorrectas = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Game");
        this.IniciarJuego();
    }
    
    public int numeroAleatorio(){
        return(int)(Math.random()*6);
    }
    
    public String generarPalabra(){
        String[]palabras = {
            "Java",
            "Python",
            "Exoloit",
            "Seguridad",
            "Datos",
            "Informe"
        };
        int indice = numeroAleatorio();
        return palabras[indice];
    }
    
    public void IniciarJuego(){
        String palabra = generarPalabra();
        txt_palabra.setText(palabra);
        numeroVidas = 5;
        txt_intentos.setText("" + numeroVidas);
    }
    
    public void validarRespuesta(String opcUsuario){
        Programador objProgramador = new Programador();
        Hacker objHacker = new Hacker();
        AnalistaDatos objAnalista = new AnalistaDatos();
        
        Boolean aux;
        
        String palabra = txt_palabra.getText();
        
        if (palabra.equals("Java")||palabra.equals("Python")){
            aux = objProgramador.resolverProblema("Programador", opcUsuario);
        }else if (palabra.equals("Exploit") || palabra.equals("Seguridad")){
            aux = objHacker.resolverProblema("Hacker", opcUsuario);
        }else{
            aux = objAnalista.resolverProblema("Analista", opcUsuario);
        }
        
        this.gestionVidas(aux);
        this.controlJuego(aux);
    }
    
    public void gestionVidas(Boolean aux){
        if(!aux){
            numeroVidas -= 1;
        }else{
            String palabra = generarPalabra();
            txt_palabra.setText(palabra);
            JOptionPane.showMessageDialog(this, "Respuesta Correcta");
        }
        if(numeroVidas == 0 ){
            JOptionPane.showMessageDialog(this, "Game Over");
        }
        txt_intentos.setText("" + numeroVidas);
    }
    
    public void controlJuego(Boolean res){
        System.out.println(res);
        if(res == true){
            resCorrectas = resCorrectas + 1 ;
        }
        if(resCorrectas > 4){
            JOptionPane.showMessageDialog(this, "WIN");
            this.IniciarJuego();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_palabra = new javax.swing.JLabel();
        btn_programador = new javax.swing.JButton();
        btn_hacker = new javax.swing.JButton();
        btn_analista = new javax.swing.JButton();
        txt_intentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_palabra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_palabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_palabra.setText("Palabra");
        getContentPane().add(txt_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 90, 40));

        btn_programador.setText("Programador");
        btn_programador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_programadorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_programador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 223, 120, 60));

        btn_hacker.setText("Hacker");
        btn_hacker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hackerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hacker, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 223, 140, 60));

        btn_analista.setText("Analista de Datos");
        btn_analista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analistaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_analista, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 223, 140, 60));

        txt_intentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_intentos.setText("Intentos #");
        getContentPane().add(txt_intentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 20, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_programadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_programadorActionPerformed
        // TODO add your handling code here:
        this.validarRespuesta("Programador");
        
        ImageIcon programerIcon = new ImageIcon(
        getClass().getResource("programmer_image.jpg")
        );
        Icon img_imagen = new ImageIcon(
        programerIcon
            .getImage()
            .getScaledInstance(
                btn_programador.getWidth(),  // Ancho del JLabel
                btn_programador.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    btn_programador.setIcon(img_imagen);
       
    }//GEN-LAST:event_btn_programadorActionPerformed

    private void btn_hackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hackerActionPerformed
        // TODO add your handling code here:
        this.validarRespuesta("Hacker");
        
        ImageIcon hackerIcon = new ImageIcon(
        getClass().getResource("hacker_image.png")
        );
        Icon img_imagen = new ImageIcon(
        hackerIcon
            .getImage()
            .getScaledInstance(
                btn_hacker.getWidth(),  // Ancho del JLabel
                btn_hacker.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    btn_hacker.setIcon(img_imagen);
       
        
    }//GEN-LAST:event_btn_hackerActionPerformed

    private void btn_analistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analistaActionPerformed
        // TODO add your handling code here:
        this.validarRespuesta("Analista");
        
        ImageIcon analistaIcon = new ImageIcon(
        getClass().getResource("data_analyst.jpg")
        );
        Icon img_imagen = new ImageIcon(
        analistaIcon
            .getImage()
            .getScaledInstance(
                btn_analista.getWidth(),  // Ancho del JLabel
                btn_analista.getHeight(), // Alto del JLabel
                Image.SCALE_SMOOTH     // Algoritmo de escalado de alta calidad
            )
    );

    // 3. Establecer el icono escalado en el JLabel
    btn_analista.setIcon(img_imagen);
       
    }//GEN-LAST:event_btn_analistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analista;
    private javax.swing.JButton btn_hacker;
    private javax.swing.JButton btn_programador;
    private javax.swing.JLabel txt_intentos;
    private javax.swing.JLabel txt_palabra;
    // End of variables declaration//GEN-END:variables
}
